export const HTTP_UNAUTHORIZED = 'HTTP_UNAUTHORIZED';
export const HTTP_SERVER_UNAVAILABLE = 'HTTP_SERVER_UNAVAILABLE';
export const HTTP_ERROR_INTERNET_LOST = 'HTTP_ERROR_INTERNET_LOST';
export const BEARER_TOKEN_NAME = 'BEARER_TOKEN_NAME';
