import {rWidth} from 'utils';

export const margin = {
  ml12: {marginLeft: rWidth(12)},
  ml15: {marginLeft: rWidth(15)},
  ml7: {marginLeft: rWidth(7)},
  ml5: {marginLeft: rWidth(5)},
  mh15: {marginHorizontal: rWidth(15)},
  mh5: {marginHorizontal: rWidth(5)},
  mh25: {marginHorizontal: rWidth(25)},
  mb5: {marginBottom: rWidth(5)},
  mt3: {marginTop: rWidth(3)},
  mt5: {marginTop: rWidth(5)},
  mt10: {marginTop: rWidth(10)},
  mt15: {marginTop: rWidth(15)},
  mt20: {marginTop: rWidth(20)},
  mr5: {marginRight: rWidth(5)},
  mr7: {marginRight: rWidth(7)},
  mr10: {marginRight: rWidth(10)},
  'mb-10': {marginBottom: -rWidth(10)},
};
export const padding = {
  p10: {padding: rWidth(10)},
  pl10: {paddingLeft: rWidth(10)},
  ph7: {paddingHorizontal: rWidth(7)},
  ph6: {paddingHorizontal: rWidth(6)},
  ph4: {paddingHorizontal: rWidth(4)},
  pt10: {paddingTop: rWidth(10)},
  ph10: {paddingHorizontal: rWidth(10)},
  ph11: {paddingHorizontal: rWidth(11)},
  pv10: {paddingVertical: rWidth(10)},
  pv15: {paddingVertical: rWidth(15)},
  ph15: {paddingHorizontal: rWidth(15)},
  ph12: {paddingHorizontal: rWidth(12)},
  ph20: {paddingHorizontal: rWidth(20)},
  pb5: {paddingBottom: rWidth(5)},
  pb7: {paddingBottom: rWidth(7)},
  pb9: {paddingBottom: rWidth(9)},
  pb10: {paddingBottom: rWidth(10)},
  pb15: {paddingBottom: rWidth(15)},
  pb18: {paddingBottom: rWidth(18)},
};
